### ISSUE TITLE
Exclude paths

### ISSUE THREAD

**Issue by jepperaskdk** [jepperaskdk/pydoctest#20]
Implement exclude_paths. Test with fnmatch so we don't have to glob all exclude files?

Should be implemented in `main.discover_modules`

**Comment by hhalaby** [comment]
@jepperaskdk Is there a way to exclude certain functions based on their name, for example, skip functions that start with underscore ?

**Comment by jepperaskdk** [comment]
0.1.17 adds support for `exclude_paths` (`--exclude-paths` in cli). 
@hhalaby lets track excluding functions, methods, classes in a separate issue. :)
