### ISSUE TITLE
Add Numpy parser

### ISSUE THREAD

**Issue by brainelectronics** [jepperaskdk/pydoctest#23]
Thank you for this great package! Really like it.
I'm currently using `reStructuredText` format as shown below, the only currently available google parser is not fully sufficient on that.
So I kindly raise this issue here as mentioned in your readme :) 

My documentation
```
def function(asdf: int) -> int:
    """
    Some description

    :param      asdf:  The asdf variable
    :type       asdf:  list

    :returns:   Something else
    :rtype:     int
    """
    return 2
```

The current output
```
Function: <function function at 0x03205340> FAIL | Return type differ. Expected (from signature) <class 'int'>, but got (in docs) <class 'NoneType'>.
```

**Comment by jepperaskdk** [comment]
Awesome! I'll start a branch for this. :)

**Comment by brainelectronics** [comment]
Yes, agree on that. I've already heard it's named "numpy style". Thought this would fit better as you already had an empty numpy parser class

**Comment by jepperaskdk** [comment]
@brainelectronics I've released it as version 0.1.13.

**Comment by brainelectronics** [comment]
so yes, not throwing an error on / parsing sucessfully `:type arg: <PYTHON_TYPE>, optional` for `arg: Optional[<PYTHON_TYPE>]` would be great, otherwise this would require a lot of changes which potentially introduce some bugs.
The errors in lines you mentioned were on purpose. The flake8, unittests and pydoctests run in parallel to get the fastest possible feedback. I was not aware that pydoctests also secretly checks that. But that can simply be changed on my setup.
Really appreciate your fast feedback and resolving the issues!

**Comment by jepperaskdk** [comment]
@brainelectronics  I'll close this now, but let me know if you still have issues with the parser. :)
