### ISSUE TITLE
Exclude patterns

### ISSUE THREAD

**Issue by jepperaskdk** [jepperaskdk/pydoctest#36]
Suggestion by @hhalaby to add exclude-patterns for classes, methods and functions.

The suggestion was a boolean, to disable all/none of the 3 types, however, I think the solution will be more useful if patterns are given instead.

So for each of the three types, add these options (classes as example):
CLI: `pydoctest --exclude-classes "Test*"`
JSON: `exclude_classes: ["Test*"]`

Here, "Test*" matches all class-names that start with "Test". To exclude all classes, you would just do "*". Private methods would be "__\*" and so on.
What do you think of this solution @hhalaby?

**Comment by hhalaby** [comment]
Pattern matching is a great solution instead of a boolean but I'm afraid the patterns you've suggestes might be too greedy and some trial and error might be needed.

Wildcards ("*") are always known to have edge cases.

Once you do a working solution ping me so I take a look

**Comment by jepperaskdk** [comment]
Released in [0.1.20](https://github.com/jepperaskdk/pydoctest/releases/tag/0.1.20)
