### ISSUE TITLE
Missing support for optional argument in numpy format?

### ISSUE THREAD

**Issue by Risitop** [jepperaskdk/pydoctest#50]
Hi, thank you very much for developing this great tool.

One question though, it seems like pydoctest is right now unable to parse optional arguments:

```python
def f(a: int = 0) -> int:
    """blabla
    
    Parameters
    ----------
    a: int, optional
        blabla, by default 0

    Returns
    -------
    int
        Adds one to the result
    """
    return a + 1
```

This `, optional` keyword being standard in numpy, would you have any tip to avoid this issue and allowing the package to parse functions with optional parameters? Thanks!

**Comment by jepperaskdk** [comment]
Thanks for posting this. Do you get an error?
It might be that the numpy parser attempts to parse the whole `int, optional` as a type, but instead it should account for this exception.

So as a minimum it should verify the type (int), but I guess it would be cool if it also spotted misplaced ", optional"? Not sure if possible though - I will have a look!

**Comment by Risitop** [comment]
Hi Jeppe, thanks a lot for this fast answer. I will try to replicate the issue on a minimal example, as it seems to be a little bit more complicated than what I first thought to make a simple failing case.

**Comment by jepperaskdk** [comment]
I've created a PR here: https://github.com/jepperaskdk/pydoctest/pull/51

There's a problem with the code-coverage tool - I will try to resolve it.

**Comment by jepperaskdk** [comment]
I've disabled codecov since it seems to be broken. I've released pydoctest 0.2.0 which should support optional - can you verify that it solves your problem? :)

**Comment by Risitop** [comment]
Yes, works well, thanks! 🙏

**Comment by jepperaskdk** [comment]
Great, thanks for finding this. I'll close this then - let me know if you find something else. 😁
